### ISSUE TITLE
Congratulations!!!!!!!

### ISSUE THREAD

**Issue by goshlanguage** [nateinaction/wedding.nateanddanielle.love#1]
This is kind of a non-issue but:

Congrats Nate and Danielle!
===
![yay](https://media.giphy.com/media/l4HodBpDmoMA5p9bG/giphy.gif)
🎉🎉🎉

**Comment by nateinaction** [comment]
Thanks Hartje! Miss you man!

**Comment by goshlanguage** [comment]
Likewise buddy. Hope all is well.
